### ISSUE TITLE
SharpSvn.dll Error :|

### ISSUE THREAD

**Issue by ImExiled** [Clef-0/FMM-Legacy#23]
Welp. Imgur wouldn't let me upload it, so I threw it up on my own website.

This error occurs every time i try to download mods, weather or not I have vc redist 2005 or not.

http://electricgaming.ga/ncs/blog/wp-content/uploads/2016/09/FMM_2016-09-14_15-14-25.png

**Comment by Clef-0** [comment]
You need to extract SharpSvn.dll from the zip FMM came in.
