### ISSUE TITLE
Zipped mod packages

### ISSUE THREAD

**Issue by dany5639** [Clef-0/FMM-Legacy#3]
The zip would need to have a proper folder structure.  
As example: 
reachSniper_V1.0.0.zip / mods / tagMods / reachSniper 
or similar, in order for users to not mess with unzipping into the right folder. So in this case, FMM will always need to unzip it into the game's root folder.
ALL the zip mods should be dropped in mods/tagMods or similar.

**Comment by Clef-0** [comment]
Changed my mind on the necessity of this - gonna close. No idea where a user would put the zips or identify a compatible zip from a non-compatible one.
